# Generated by Django 6.0.5 on 2026-06-02 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='제목')),
                ('authors', models.CharField(blank=True, help_text='쉼표 구분', max_length=500, verbose_name='저자')),
                ('affiliations', models.CharField(blank=True, help_text='쉼표 구분', max_length=500, verbose_name='소속')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='발행일')),
                ('raw_text', models.TextField(blank=True, verbose_name='본문 원문')),
                ('summary', models.TextField(blank=True, verbose_name='AI 요약')),
                ('url', models.URLField(blank=True, max_length=1000, verbose_name='원본 URL')),
                ('file_path', models.CharField(blank=True, max_length=1000, verbose_name='로컬 파일 경로')),
                ('status', models.CharField(choices=[('collected', '수집됨'), ('extracted', '본문추출됨'), ('embedded', '임베딩됨'), ('analyzed', '분석완료')], default='collected', max_length=12, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '문서',
                'verbose_name_plural': '문서',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='키워드')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='분류')),
                ('lifecycle', models.CharField(blank=True, choices=[('성장', '성장'), ('신규', '신규'), ('쇠퇴', '쇠퇴'), ('변동', '변동'), ('정체', '정체')], max_length=10, verbose_name='라이프사이클')),
            ],
            options={
                'verbose_name': '키워드',
                'verbose_name_plural': '키워드',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='이름')),
                ('type', models.CharField(choices=[('paper', '논문/학회지'), ('blog', '블로그'), ('news', '뉴스')], default='paper', max_length=10, verbose_name='유형')),
                ('url', models.URLField(blank=True, verbose_name='사이트 URL')),
                ('rss_url', models.URLField(blank=True, help_text='자동 수집용 (4단계)', verbose_name='RSS 주소')),
                ('is_active', models.BooleanField(default=True, verbose_name='수집 활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '출처',
                'verbose_name_plural': '출처',
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순번')),
                ('text', models.TextField(verbose_name='조각 본문')),
                ('embedding_id', models.CharField(blank=True, max_length=100, verbose_name='벡터 ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='insight.document', verbose_name='문서')),
            ],
            options={
                'verbose_name': '본문조각',
                'verbose_name_plural': '본문조각',
                'ordering': ['document', 'order'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='documents', to='insight.keyword', verbose_name='키워드'),
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='insight.source', verbose_name='출처'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('file_path', ''), _negated=True), fields=('source', 'file_path'), name='uniq_source_filepath'),
        ),
    ]
