# Generated by Django 6.0.5 on 2026-06-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(blank=True, help_text='뉴스 분류: AI/Robot/Security/Data/IT 등', max_length=30, verbose_name='카테고리'),
        ),
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.URLField(blank=True, max_length=1000, verbose_name='썸네일 이미지'),
        ),
    ]
