# Generated by Django 6.0.5 on 2026-06-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0002_document_category_document_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='engine',
            field=models.CharField(blank=True, help_text='요약에 사용한 모델: EXAONE/Claude 등', max_length=50, verbose_name='요약 엔진'),
        ),
    ]
