# Generated by Django 6.0.5 on 2026-06-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0003_document_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='metric',
            field=models.CharField(blank=True, help_text='논문 수집 근거: 인용수/추천수/게재 학회 등', max_length=80, verbose_name='저명도 지표'),
        ),
    ]
