# Generated by Django 6.0.5 on 2026-06-12 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0004_document_metric'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArxivDocument',
            fields=[
            ],
            options={
                'verbose_name': 'arXiv',
                'verbose_name_plural': 'arXiv',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insight.document',),
        ),
        migrations.CreateModel(
            name='HFDocument',
            fields=[
            ],
            options={
                'verbose_name': 'HF Papers',
                'verbose_name_plural': 'HF Papers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insight.document',),
        ),
        migrations.CreateModel(
            name='JournalDocument',
            fields=[
            ],
            options={
                'verbose_name': '정보과학회지',
                'verbose_name_plural': '정보과학회지',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insight.document',),
        ),
        migrations.CreateModel(
            name='NewsDocument',
            fields=[
            ],
            options={
                'verbose_name': '뉴스',
                'verbose_name_plural': '뉴스',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insight.document',),
        ),
        migrations.CreateModel(
            name='ScholarDocument',
            fields=[
            ],
            options={
                'verbose_name': 'Semantic Scholar',
                'verbose_name_plural': 'Semantic Scholar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insight.document',),
        ),
    ]
