# Generated by Django 6.0.5 on 2026-06-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0005_arxivdocument_hfdocument_journaldocument_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hfdocument',
            options={'verbose_name': 'HuggingFace Papers', 'verbose_name_plural': 'HuggingFace Papers'},
        ),
    ]
