# Generated by Django 6.0.5 on 2026-06-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0006_alter_hfdocument_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embed_model',
            field=models.CharField(blank=True, editable=False, max_length=50, verbose_name='임베딩 모델'),
        ),
        migrations.AddField(
            model_name='document',
            name='embedding',
            field=models.BinaryField(blank=True, null=True, verbose_name='임베딩 벡터'),
        ),
    ]
