# Generated by Django 6.0.5 on 2026-06-15 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0007_document_embed_model_document_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDocument',
            fields=[
            ],
            options={
                'verbose_name': '연구소 블로그',
                'verbose_name_plural': '연구소 블로그',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insight.document',),
        ),
    ]
