# Generated by Django 6.0.5 on 2026-06-16 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0008_blogdocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogDocument',
        ),
        migrations.CreateModel(
            name='AnthropicDocument',
            fields=[
            ],
            options={
                'verbose_name': 'Anthropic Blog',
                'verbose_name_plural': 'Anthropic Blog',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insight.document',),
        ),
        migrations.CreateModel(
            name='BAIRDocument',
            fields=[
            ],
            options={
                'verbose_name': 'BAIR Blog',
                'verbose_name_plural': 'BAIR Blog',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insight.document',),
        ),
        migrations.CreateModel(
            name='DeepMindDocument',
            fields=[
            ],
            options={
                'verbose_name': 'DeepMind Blog',
                'verbose_name_plural': 'DeepMind Blog',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insight.document',),
        ),
        migrations.CreateModel(
            name='MSResearchDocument',
            fields=[
            ],
            options={
                'verbose_name': 'Microsoft Research Blog',
                'verbose_name_plural': 'Microsoft Research Blog',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insight.document',),
        ),
        migrations.CreateModel(
            name='OpenAIDocument',
            fields=[
            ],
            options={
                'verbose_name': 'OpenAI Blog',
                'verbose_name_plural': 'OpenAI Blog',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('insight.document',),
        ),
    ]
