"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env 파일이 있으면 환경변수로 로드 (SUPABASE_*, DJANGO_* 등). git 에는 제외됨.
from dotenv import load_dotenv  # noqa: E402
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 운영 서버에서는 환경변수 DJANGO_SECRET_KEY 로 반드시 지정한다.
# (아래 기본값은 로컬 개발 전용 — 공개돼도 무방하도록 dev 표시)
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-dev-only-local-key-change-in-production',
)

# SECURITY WARNING: don't run with debug turned on in production!
# 환경변수 DJANGO_DEBUG=0 이면 운영 모드. 기본은 개발(True).
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

# 운영 서버 도메인/IP는 환경변수 DJANGO_ALLOWED_HOSTS 에 쉼표로 구분해 넣는다.
# 예: DJANGO_ALLOWED_HOSTS=123.45.67.89,mydomain.com
ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()
]

# HTTPS 도메인(예: Tailscale Funnel)에서 폼 제출(로그인/챗봇)이 되도록 CSRF 신뢰 출처 등록.
# Django는 Origin 헤더를 포트까지 정확히 비교하므로, 포트 없는 버전과 :8443(Funnel) 둘 다 등록.
_csrf_hosts = [
    h for h in ALLOWED_HOSTS
    if h not in ("localhost", "127.0.0.1") and not h.replace(".", "").isdigit()
]
CSRF_TRUSTED_ORIGINS = []
for h in _csrf_hosts:
    CSRF_TRUSTED_ORIGINS.append(f"https://{h}")
    CSRF_TRUSTED_ORIGINS.append(f"https://{h}:8443")   # Tailscale Funnel 포트
# 환경변수로 추가 지정 가능 (쉼표 구분, 전체 origin 형태)
_extra = os.environ.get("DJANGO_CSRF_ORIGINS", "")
CSRF_TRUSTED_ORIGINS += [o.strip() for o in _extra.split(",") if o.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'insight',
    'dashboard',
    'chatbot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 운영 모드에서 정적파일(CSS/JS) 서빙 (SecurityMiddleware 바로 다음이 표준 위치)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # [개발 편의용] 템플릿에서 {{ is_debug }} 로 DEBUG 여부 사용 (입장 버튼 노출용)
                'dashboard.context_processors.debug_flag',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# 운영 배포 시 `collectstatic` 으로 정적파일을 모을 위치
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: 운영 모드에서 정적파일을 압축·캐싱하여 gunicorn이 직접 서빙
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
